apiVersion: v1
kind: Service
metadata:
    name: steevaavoopipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 8081 
    selector:
        app: steevaavoopipelinesjavascriptdocker
